[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "reinforced-lib"
version = "1.1.4"
requires-python = ">=3.9, <4"

description = "Reinforcement learning library"
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["deep-reinforcement-learning", "jax", "library", "machine-learning", "reinforcement-learning"]

authors = [
    {name = "Maksymilian Wojnar", email = "mwojnar@agh.edu.pl"},
    {name = "Wojciech Ciężobka", email = "wciezobka@agh.edu.pl"}
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Typing :: Typed"
]

dependencies = [
    "chex~=0.1.86",
    "cloudpickle~=3.0.0",
    "flax~=0.8.5",
    "gymnasium~=0.29.1",
    "jax~=0.4.30",
    "jaxlib~=0.4.30",
    "lz4~=4.3.3",
    "matplotlib~=3.9.1",
    "optax~=0.2.3",
    "tensorboardX~=2.6.2.2",
    "wandb~=0.17.6"
]

[project.optional-dependencies]
docs = [
    "sphinx~=7.4.7",
    "sphinx-rtd-theme~=2.0.0"
]
full = [
    "joblib~=1.4.2",
    # "ns3-ai==1.0.2",
    "pygame~=2.6.0",
    "seaborn~=0.13.2",
    "tensorflow~=2.17.0"
]
